// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/observatory/config.proto

package com.v2ray.core.app.observatory;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.observatory.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * &#64;Document The selectors for outbound under observation
   * </pre>
   *
   * <code>repeated string subject_selector = 2;</code>
   * @return A list containing the subjectSelector.
   */
  java.util.List<java.lang.String>
      getSubjectSelectorList();
  /**
   * <pre>
   * &#64;Document The selectors for outbound under observation
   * </pre>
   *
   * <code>repeated string subject_selector = 2;</code>
   * @return The count of subjectSelector.
   */
  int getSubjectSelectorCount();
  /**
   * <pre>
   * &#64;Document The selectors for outbound under observation
   * </pre>
   *
   * <code>repeated string subject_selector = 2;</code>
   * @param index The index of the element to return.
   * @return The subjectSelector at the given index.
   */
  java.lang.String getSubjectSelector(int index);
  /**
   * <pre>
   * &#64;Document The selectors for outbound under observation
   * </pre>
   *
   * <code>repeated string subject_selector = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the subjectSelector at the given index.
   */
  com.google.protobuf.ByteString
      getSubjectSelectorBytes(int index);

  /**
   * <code>string probe_url = 3;</code>
   * @return The probeUrl.
   */
  java.lang.String getProbeUrl();
  /**
   * <code>string probe_url = 3;</code>
   * @return The bytes for probeUrl.
   */
  com.google.protobuf.ByteString
      getProbeUrlBytes();

  /**
   * <code>int64 probe_interval = 4;</code>
   * @return The probeInterval.
   */
  long getProbeInterval();
}
