// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/observatory/config.proto

package com.v2ray.core.app.observatory;

/**
 * Protobuf type {@code v2ray.core.app.observatory.OutboundStatus}
 */
public final class OutboundStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.app.observatory.OutboundStatus)
    OutboundStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OutboundStatus.newBuilder() to construct.
  private OutboundStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OutboundStatus() {
    lastErrorReason_ = "";
    outboundTag_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OutboundStatus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.app.observatory.ConfigOuterClass.internal_static_v2ray_core_app_observatory_OutboundStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.app.observatory.ConfigOuterClass.internal_static_v2ray_core_app_observatory_OutboundStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.app.observatory.OutboundStatus.class, com.v2ray.core.app.observatory.OutboundStatus.Builder.class);
  }

  public static final int ALIVE_FIELD_NUMBER = 1;
  private boolean alive_;
  /**
   * <pre>
   * &#64;Document Whether this outbound is usable
   *&#64;Restriction ReadOnlyForUser
   * </pre>
   *
   * <code>bool alive = 1;</code>
   * @return The alive.
   */
  @java.lang.Override
  public boolean getAlive() {
    return alive_;
  }

  public static final int DELAY_FIELD_NUMBER = 2;
  private long delay_;
  /**
   * <pre>
   * &#64;Document The time for probe request to finish.
   *&#64;Type time.ms
   *&#64;Restriction ReadOnlyForUser
   * </pre>
   *
   * <code>int64 delay = 2;</code>
   * @return The delay.
   */
  @java.lang.Override
  public long getDelay() {
    return delay_;
  }

  public static final int LAST_ERROR_REASON_FIELD_NUMBER = 3;
  private volatile java.lang.Object lastErrorReason_;
  /**
   * <pre>
   * &#64;Document The last error caused this outbound failed to relay probe request
   *&#64;Restriction NotMachineReadable
   * </pre>
   *
   * <code>string last_error_reason = 3;</code>
   * @return The lastErrorReason.
   */
  @java.lang.Override
  public java.lang.String getLastErrorReason() {
    java.lang.Object ref = lastErrorReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastErrorReason_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;Document The last error caused this outbound failed to relay probe request
   *&#64;Restriction NotMachineReadable
   * </pre>
   *
   * <code>string last_error_reason = 3;</code>
   * @return The bytes for lastErrorReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastErrorReasonBytes() {
    java.lang.Object ref = lastErrorReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastErrorReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OUTBOUND_TAG_FIELD_NUMBER = 4;
  private volatile java.lang.Object outboundTag_;
  /**
   * <pre>
   * &#64;Document The outbound tag for this Server
   *&#64;Type id.outboundTag
   * </pre>
   *
   * <code>string outbound_tag = 4;</code>
   * @return The outboundTag.
   */
  @java.lang.Override
  public java.lang.String getOutboundTag() {
    java.lang.Object ref = outboundTag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outboundTag_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;Document The outbound tag for this Server
   *&#64;Type id.outboundTag
   * </pre>
   *
   * <code>string outbound_tag = 4;</code>
   * @return The bytes for outboundTag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutboundTagBytes() {
    java.lang.Object ref = outboundTag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outboundTag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_SEEN_TIME_FIELD_NUMBER = 5;
  private long lastSeenTime_;
  /**
   * <pre>
   * &#64;Document The time this outbound is known to be alive
   *&#64;Type id.outboundTag
   * </pre>
   *
   * <code>int64 last_seen_time = 5;</code>
   * @return The lastSeenTime.
   */
  @java.lang.Override
  public long getLastSeenTime() {
    return lastSeenTime_;
  }

  public static final int LAST_TRY_TIME_FIELD_NUMBER = 6;
  private long lastTryTime_;
  /**
   * <pre>
   * &#64;Document The time this outbound is tried
   *&#64;Type id.outboundTag
   * </pre>
   *
   * <code>int64 last_try_time = 6;</code>
   * @return The lastTryTime.
   */
  @java.lang.Override
  public long getLastTryTime() {
    return lastTryTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (alive_ != false) {
      output.writeBool(1, alive_);
    }
    if (delay_ != 0L) {
      output.writeInt64(2, delay_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastErrorReason_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastErrorReason_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(outboundTag_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, outboundTag_);
    }
    if (lastSeenTime_ != 0L) {
      output.writeInt64(5, lastSeenTime_);
    }
    if (lastTryTime_ != 0L) {
      output.writeInt64(6, lastTryTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (alive_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, alive_);
    }
    if (delay_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, delay_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastErrorReason_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastErrorReason_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(outboundTag_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, outboundTag_);
    }
    if (lastSeenTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, lastSeenTime_);
    }
    if (lastTryTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, lastTryTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.app.observatory.OutboundStatus)) {
      return super.equals(obj);
    }
    com.v2ray.core.app.observatory.OutboundStatus other = (com.v2ray.core.app.observatory.OutboundStatus) obj;

    if (getAlive()
        != other.getAlive()) return false;
    if (getDelay()
        != other.getDelay()) return false;
    if (!getLastErrorReason()
        .equals(other.getLastErrorReason())) return false;
    if (!getOutboundTag()
        .equals(other.getOutboundTag())) return false;
    if (getLastSeenTime()
        != other.getLastSeenTime()) return false;
    if (getLastTryTime()
        != other.getLastTryTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAlive());
    hash = (37 * hash) + DELAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDelay());
    hash = (37 * hash) + LAST_ERROR_REASON_FIELD_NUMBER;
    hash = (53 * hash) + getLastErrorReason().hashCode();
    hash = (37 * hash) + OUTBOUND_TAG_FIELD_NUMBER;
    hash = (53 * hash) + getOutboundTag().hashCode();
    hash = (37 * hash) + LAST_SEEN_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastSeenTime());
    hash = (37 * hash) + LAST_TRY_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastTryTime());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.app.observatory.OutboundStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.observatory.OutboundStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.observatory.OutboundStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.observatory.OutboundStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.observatory.OutboundStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.observatory.OutboundStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.observatory.OutboundStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.observatory.OutboundStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.observatory.OutboundStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.observatory.OutboundStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.observatory.OutboundStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.observatory.OutboundStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.app.observatory.OutboundStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code v2ray.core.app.observatory.OutboundStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.app.observatory.OutboundStatus)
      com.v2ray.core.app.observatory.OutboundStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.app.observatory.ConfigOuterClass.internal_static_v2ray_core_app_observatory_OutboundStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.app.observatory.ConfigOuterClass.internal_static_v2ray_core_app_observatory_OutboundStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.app.observatory.OutboundStatus.class, com.v2ray.core.app.observatory.OutboundStatus.Builder.class);
    }

    // Construct using com.v2ray.core.app.observatory.OutboundStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      alive_ = false;

      delay_ = 0L;

      lastErrorReason_ = "";

      outboundTag_ = "";

      lastSeenTime_ = 0L;

      lastTryTime_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.app.observatory.ConfigOuterClass.internal_static_v2ray_core_app_observatory_OutboundStatus_descriptor;
    }

    @java.lang.Override
    public com.v2ray.core.app.observatory.OutboundStatus getDefaultInstanceForType() {
      return com.v2ray.core.app.observatory.OutboundStatus.getDefaultInstance();
    }

    @java.lang.Override
    public com.v2ray.core.app.observatory.OutboundStatus build() {
      com.v2ray.core.app.observatory.OutboundStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.v2ray.core.app.observatory.OutboundStatus buildPartial() {
      com.v2ray.core.app.observatory.OutboundStatus result = new com.v2ray.core.app.observatory.OutboundStatus(this);
      result.alive_ = alive_;
      result.delay_ = delay_;
      result.lastErrorReason_ = lastErrorReason_;
      result.outboundTag_ = outboundTag_;
      result.lastSeenTime_ = lastSeenTime_;
      result.lastTryTime_ = lastTryTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.app.observatory.OutboundStatus) {
        return mergeFrom((com.v2ray.core.app.observatory.OutboundStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.app.observatory.OutboundStatus other) {
      if (other == com.v2ray.core.app.observatory.OutboundStatus.getDefaultInstance()) return this;
      if (other.getAlive() != false) {
        setAlive(other.getAlive());
      }
      if (other.getDelay() != 0L) {
        setDelay(other.getDelay());
      }
      if (!other.getLastErrorReason().isEmpty()) {
        lastErrorReason_ = other.lastErrorReason_;
        onChanged();
      }
      if (!other.getOutboundTag().isEmpty()) {
        outboundTag_ = other.outboundTag_;
        onChanged();
      }
      if (other.getLastSeenTime() != 0L) {
        setLastSeenTime(other.getLastSeenTime());
      }
      if (other.getLastTryTime() != 0L) {
        setLastTryTime(other.getLastTryTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              alive_ = input.readBool();

              break;
            } // case 8
            case 16: {
              delay_ = input.readInt64();

              break;
            } // case 16
            case 26: {
              lastErrorReason_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              outboundTag_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 40: {
              lastSeenTime_ = input.readInt64();

              break;
            } // case 40
            case 48: {
              lastTryTime_ = input.readInt64();

              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private boolean alive_ ;
    /**
     * <pre>
     * &#64;Document Whether this outbound is usable
     *&#64;Restriction ReadOnlyForUser
     * </pre>
     *
     * <code>bool alive = 1;</code>
     * @return The alive.
     */
    @java.lang.Override
    public boolean getAlive() {
      return alive_;
    }
    /**
     * <pre>
     * &#64;Document Whether this outbound is usable
     *&#64;Restriction ReadOnlyForUser
     * </pre>
     *
     * <code>bool alive = 1;</code>
     * @param value The alive to set.
     * @return This builder for chaining.
     */
    public Builder setAlive(boolean value) {
      
      alive_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;Document Whether this outbound is usable
     *&#64;Restriction ReadOnlyForUser
     * </pre>
     *
     * <code>bool alive = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlive() {
      
      alive_ = false;
      onChanged();
      return this;
    }

    private long delay_ ;
    /**
     * <pre>
     * &#64;Document The time for probe request to finish.
     *&#64;Type time.ms
     *&#64;Restriction ReadOnlyForUser
     * </pre>
     *
     * <code>int64 delay = 2;</code>
     * @return The delay.
     */
    @java.lang.Override
    public long getDelay() {
      return delay_;
    }
    /**
     * <pre>
     * &#64;Document The time for probe request to finish.
     *&#64;Type time.ms
     *&#64;Restriction ReadOnlyForUser
     * </pre>
     *
     * <code>int64 delay = 2;</code>
     * @param value The delay to set.
     * @return This builder for chaining.
     */
    public Builder setDelay(long value) {
      
      delay_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;Document The time for probe request to finish.
     *&#64;Type time.ms
     *&#64;Restriction ReadOnlyForUser
     * </pre>
     *
     * <code>int64 delay = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDelay() {
      
      delay_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object lastErrorReason_ = "";
    /**
     * <pre>
     * &#64;Document The last error caused this outbound failed to relay probe request
     *&#64;Restriction NotMachineReadable
     * </pre>
     *
     * <code>string last_error_reason = 3;</code>
     * @return The lastErrorReason.
     */
    public java.lang.String getLastErrorReason() {
      java.lang.Object ref = lastErrorReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastErrorReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;Document The last error caused this outbound failed to relay probe request
     *&#64;Restriction NotMachineReadable
     * </pre>
     *
     * <code>string last_error_reason = 3;</code>
     * @return The bytes for lastErrorReason.
     */
    public com.google.protobuf.ByteString
        getLastErrorReasonBytes() {
      java.lang.Object ref = lastErrorReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastErrorReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;Document The last error caused this outbound failed to relay probe request
     *&#64;Restriction NotMachineReadable
     * </pre>
     *
     * <code>string last_error_reason = 3;</code>
     * @param value The lastErrorReason to set.
     * @return This builder for chaining.
     */
    public Builder setLastErrorReason(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastErrorReason_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;Document The last error caused this outbound failed to relay probe request
     *&#64;Restriction NotMachineReadable
     * </pre>
     *
     * <code>string last_error_reason = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastErrorReason() {
      
      lastErrorReason_ = getDefaultInstance().getLastErrorReason();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;Document The last error caused this outbound failed to relay probe request
     *&#64;Restriction NotMachineReadable
     * </pre>
     *
     * <code>string last_error_reason = 3;</code>
     * @param value The bytes for lastErrorReason to set.
     * @return This builder for chaining.
     */
    public Builder setLastErrorReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastErrorReason_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object outboundTag_ = "";
    /**
     * <pre>
     * &#64;Document The outbound tag for this Server
     *&#64;Type id.outboundTag
     * </pre>
     *
     * <code>string outbound_tag = 4;</code>
     * @return The outboundTag.
     */
    public java.lang.String getOutboundTag() {
      java.lang.Object ref = outboundTag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outboundTag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;Document The outbound tag for this Server
     *&#64;Type id.outboundTag
     * </pre>
     *
     * <code>string outbound_tag = 4;</code>
     * @return The bytes for outboundTag.
     */
    public com.google.protobuf.ByteString
        getOutboundTagBytes() {
      java.lang.Object ref = outboundTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outboundTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;Document The outbound tag for this Server
     *&#64;Type id.outboundTag
     * </pre>
     *
     * <code>string outbound_tag = 4;</code>
     * @param value The outboundTag to set.
     * @return This builder for chaining.
     */
    public Builder setOutboundTag(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      outboundTag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;Document The outbound tag for this Server
     *&#64;Type id.outboundTag
     * </pre>
     *
     * <code>string outbound_tag = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutboundTag() {
      
      outboundTag_ = getDefaultInstance().getOutboundTag();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;Document The outbound tag for this Server
     *&#64;Type id.outboundTag
     * </pre>
     *
     * <code>string outbound_tag = 4;</code>
     * @param value The bytes for outboundTag to set.
     * @return This builder for chaining.
     */
    public Builder setOutboundTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      outboundTag_ = value;
      onChanged();
      return this;
    }

    private long lastSeenTime_ ;
    /**
     * <pre>
     * &#64;Document The time this outbound is known to be alive
     *&#64;Type id.outboundTag
     * </pre>
     *
     * <code>int64 last_seen_time = 5;</code>
     * @return The lastSeenTime.
     */
    @java.lang.Override
    public long getLastSeenTime() {
      return lastSeenTime_;
    }
    /**
     * <pre>
     * &#64;Document The time this outbound is known to be alive
     *&#64;Type id.outboundTag
     * </pre>
     *
     * <code>int64 last_seen_time = 5;</code>
     * @param value The lastSeenTime to set.
     * @return This builder for chaining.
     */
    public Builder setLastSeenTime(long value) {
      
      lastSeenTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;Document The time this outbound is known to be alive
     *&#64;Type id.outboundTag
     * </pre>
     *
     * <code>int64 last_seen_time = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastSeenTime() {
      
      lastSeenTime_ = 0L;
      onChanged();
      return this;
    }

    private long lastTryTime_ ;
    /**
     * <pre>
     * &#64;Document The time this outbound is tried
     *&#64;Type id.outboundTag
     * </pre>
     *
     * <code>int64 last_try_time = 6;</code>
     * @return The lastTryTime.
     */
    @java.lang.Override
    public long getLastTryTime() {
      return lastTryTime_;
    }
    /**
     * <pre>
     * &#64;Document The time this outbound is tried
     *&#64;Type id.outboundTag
     * </pre>
     *
     * <code>int64 last_try_time = 6;</code>
     * @param value The lastTryTime to set.
     * @return This builder for chaining.
     */
    public Builder setLastTryTime(long value) {
      
      lastTryTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;Document The time this outbound is tried
     *&#64;Type id.outboundTag
     * </pre>
     *
     * <code>int64 last_try_time = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastTryTime() {
      
      lastTryTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.app.observatory.OutboundStatus)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.app.observatory.OutboundStatus)
  private static final com.v2ray.core.app.observatory.OutboundStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.app.observatory.OutboundStatus();
  }

  public static com.v2ray.core.app.observatory.OutboundStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OutboundStatus>
      PARSER = new com.google.protobuf.AbstractParser<OutboundStatus>() {
    @java.lang.Override
    public OutboundStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OutboundStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OutboundStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.v2ray.core.app.observatory.OutboundStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

