// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/tls/config.proto

package com.v2ray.core.transport.internet.tls;

public interface CertificateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.transport.internet.tls.Certificate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * TLS certificate in x509 format.
   * </pre>
   *
   * <code>bytes Certificate = 1;</code>
   * @return The certificate.
   */
  com.google.protobuf.ByteString getCertificate();

  /**
   * <pre>
   * TLS key in x509 format.
   * </pre>
   *
   * <code>bytes Key = 2;</code>
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>.v2ray.core.transport.internet.tls.Certificate.Usage usage = 3;</code>
   * @return The enum numeric value on the wire for usage.
   */
  int getUsageValue();
  /**
   * <code>.v2ray.core.transport.internet.tls.Certificate.Usage usage = 3;</code>
   * @return The usage.
   */
  com.v2ray.core.transport.internet.tls.Certificate.Usage getUsage();
}
