// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/reverse/config.proto

package com.v2ray.core.proxy.reverse;

public interface BridgeConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.reverse.BridgeConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag = 1;</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>string domain = 2;</code>
   * @return The domain.
   */
  java.lang.String getDomain();
  /**
   * <code>string domain = 2;</code>
   * @return The bytes for domain.
   */
  com.google.protobuf.ByteString
      getDomainBytes();
}
