// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/proxyman/command/command.proto

package com.v2ray.core.app.proxyman.command;

public interface RemoveUserOperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.proxyman.command.RemoveUserOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
