// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/trojan/config.proto

package com.v2ray.core.proxy.trojan;

/**
 * Protobuf type {@code v2ray.core.proxy.trojan.ServerConfig}
 */
public final class ServerConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.proxy.trojan.ServerConfig)
    ServerConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerConfig.newBuilder() to construct.
  private ServerConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerConfig() {
    users_ = java.util.Collections.emptyList();
    fallbacks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerConfig();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.proxy.trojan.Config.internal_static_v2ray_core_proxy_trojan_ServerConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.proxy.trojan.Config.internal_static_v2ray_core_proxy_trojan_ServerConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.proxy.trojan.ServerConfig.class, com.v2ray.core.proxy.trojan.ServerConfig.Builder.class);
  }

  public static final int USERS_FIELD_NUMBER = 1;
  private java.util.List<com.v2ray.core.common.protocol.User> users_;
  /**
   * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.v2ray.core.common.protocol.User> getUsersList() {
    return users_;
  }
  /**
   * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.v2ray.core.common.protocol.UserOrBuilder> 
      getUsersOrBuilderList() {
    return users_;
  }
  /**
   * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
   */
  @java.lang.Override
  public int getUsersCount() {
    return users_.size();
  }
  /**
   * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
   */
  @java.lang.Override
  public com.v2ray.core.common.protocol.User getUsers(int index) {
    return users_.get(index);
  }
  /**
   * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
   */
  @java.lang.Override
  public com.v2ray.core.common.protocol.UserOrBuilder getUsersOrBuilder(
      int index) {
    return users_.get(index);
  }

  public static final int FALLBACKS_FIELD_NUMBER = 3;
  private java.util.List<com.v2ray.core.proxy.trojan.Fallback> fallbacks_;
  /**
   * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.v2ray.core.proxy.trojan.Fallback> getFallbacksList() {
    return fallbacks_;
  }
  /**
   * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.v2ray.core.proxy.trojan.FallbackOrBuilder> 
      getFallbacksOrBuilderList() {
    return fallbacks_;
  }
  /**
   * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
   */
  @java.lang.Override
  public int getFallbacksCount() {
    return fallbacks_.size();
  }
  /**
   * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
   */
  @java.lang.Override
  public com.v2ray.core.proxy.trojan.Fallback getFallbacks(int index) {
    return fallbacks_.get(index);
  }
  /**
   * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
   */
  @java.lang.Override
  public com.v2ray.core.proxy.trojan.FallbackOrBuilder getFallbacksOrBuilder(
      int index) {
    return fallbacks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < users_.size(); i++) {
      output.writeMessage(1, users_.get(i));
    }
    for (int i = 0; i < fallbacks_.size(); i++) {
      output.writeMessage(3, fallbacks_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < users_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, users_.get(i));
    }
    for (int i = 0; i < fallbacks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, fallbacks_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.proxy.trojan.ServerConfig)) {
      return super.equals(obj);
    }
    com.v2ray.core.proxy.trojan.ServerConfig other = (com.v2ray.core.proxy.trojan.ServerConfig) obj;

    if (!getUsersList()
        .equals(other.getUsersList())) return false;
    if (!getFallbacksList()
        .equals(other.getFallbacksList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUsersCount() > 0) {
      hash = (37 * hash) + USERS_FIELD_NUMBER;
      hash = (53 * hash) + getUsersList().hashCode();
    }
    if (getFallbacksCount() > 0) {
      hash = (37 * hash) + FALLBACKS_FIELD_NUMBER;
      hash = (53 * hash) + getFallbacksList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.proxy.trojan.ServerConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.proxy.trojan.ServerConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.proxy.trojan.ServerConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.proxy.trojan.ServerConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.proxy.trojan.ServerConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.proxy.trojan.ServerConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.proxy.trojan.ServerConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.proxy.trojan.ServerConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.proxy.trojan.ServerConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.proxy.trojan.ServerConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.proxy.trojan.ServerConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.proxy.trojan.ServerConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.proxy.trojan.ServerConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code v2ray.core.proxy.trojan.ServerConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.proxy.trojan.ServerConfig)
      com.v2ray.core.proxy.trojan.ServerConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.proxy.trojan.Config.internal_static_v2ray_core_proxy_trojan_ServerConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.proxy.trojan.Config.internal_static_v2ray_core_proxy_trojan_ServerConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.proxy.trojan.ServerConfig.class, com.v2ray.core.proxy.trojan.ServerConfig.Builder.class);
    }

    // Construct using com.v2ray.core.proxy.trojan.ServerConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
      } else {
        users_ = null;
        usersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (fallbacksBuilder_ == null) {
        fallbacks_ = java.util.Collections.emptyList();
      } else {
        fallbacks_ = null;
        fallbacksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.proxy.trojan.Config.internal_static_v2ray_core_proxy_trojan_ServerConfig_descriptor;
    }

    @java.lang.Override
    public com.v2ray.core.proxy.trojan.ServerConfig getDefaultInstanceForType() {
      return com.v2ray.core.proxy.trojan.ServerConfig.getDefaultInstance();
    }

    @java.lang.Override
    public com.v2ray.core.proxy.trojan.ServerConfig build() {
      com.v2ray.core.proxy.trojan.ServerConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.v2ray.core.proxy.trojan.ServerConfig buildPartial() {
      com.v2ray.core.proxy.trojan.ServerConfig result = new com.v2ray.core.proxy.trojan.ServerConfig(this);
      int from_bitField0_ = bitField0_;
      if (usersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          users_ = java.util.Collections.unmodifiableList(users_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.users_ = users_;
      } else {
        result.users_ = usersBuilder_.build();
      }
      if (fallbacksBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          fallbacks_ = java.util.Collections.unmodifiableList(fallbacks_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.fallbacks_ = fallbacks_;
      } else {
        result.fallbacks_ = fallbacksBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.proxy.trojan.ServerConfig) {
        return mergeFrom((com.v2ray.core.proxy.trojan.ServerConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.proxy.trojan.ServerConfig other) {
      if (other == com.v2ray.core.proxy.trojan.ServerConfig.getDefaultInstance()) return this;
      if (usersBuilder_ == null) {
        if (!other.users_.isEmpty()) {
          if (users_.isEmpty()) {
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUsersIsMutable();
            users_.addAll(other.users_);
          }
          onChanged();
        }
      } else {
        if (!other.users_.isEmpty()) {
          if (usersBuilder_.isEmpty()) {
            usersBuilder_.dispose();
            usersBuilder_ = null;
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000001);
            usersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUsersFieldBuilder() : null;
          } else {
            usersBuilder_.addAllMessages(other.users_);
          }
        }
      }
      if (fallbacksBuilder_ == null) {
        if (!other.fallbacks_.isEmpty()) {
          if (fallbacks_.isEmpty()) {
            fallbacks_ = other.fallbacks_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFallbacksIsMutable();
            fallbacks_.addAll(other.fallbacks_);
          }
          onChanged();
        }
      } else {
        if (!other.fallbacks_.isEmpty()) {
          if (fallbacksBuilder_.isEmpty()) {
            fallbacksBuilder_.dispose();
            fallbacksBuilder_ = null;
            fallbacks_ = other.fallbacks_;
            bitField0_ = (bitField0_ & ~0x00000002);
            fallbacksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFallbacksFieldBuilder() : null;
          } else {
            fallbacksBuilder_.addAllMessages(other.fallbacks_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.v2ray.core.common.protocol.User m =
                  input.readMessage(
                      com.v2ray.core.common.protocol.User.parser(),
                      extensionRegistry);
              if (usersBuilder_ == null) {
                ensureUsersIsMutable();
                users_.add(m);
              } else {
                usersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 26: {
              com.v2ray.core.proxy.trojan.Fallback m =
                  input.readMessage(
                      com.v2ray.core.proxy.trojan.Fallback.parser(),
                      extensionRegistry);
              if (fallbacksBuilder_ == null) {
                ensureFallbacksIsMutable();
                fallbacks_.add(m);
              } else {
                fallbacksBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.v2ray.core.common.protocol.User> users_ =
      java.util.Collections.emptyList();
    private void ensureUsersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        users_ = new java.util.ArrayList<com.v2ray.core.common.protocol.User>(users_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.v2ray.core.common.protocol.User, com.v2ray.core.common.protocol.User.Builder, com.v2ray.core.common.protocol.UserOrBuilder> usersBuilder_;

    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public java.util.List<com.v2ray.core.common.protocol.User> getUsersList() {
      if (usersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(users_);
      } else {
        return usersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public int getUsersCount() {
      if (usersBuilder_ == null) {
        return users_.size();
      } else {
        return usersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public com.v2ray.core.common.protocol.User getUsers(int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);
      } else {
        return usersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public Builder setUsers(
        int index, com.v2ray.core.common.protocol.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.set(index, value);
        onChanged();
      } else {
        usersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public Builder setUsers(
        int index, com.v2ray.core.common.protocol.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.set(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public Builder addUsers(com.v2ray.core.common.protocol.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(value);
        onChanged();
      } else {
        usersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public Builder addUsers(
        int index, com.v2ray.core.common.protocol.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(index, value);
        onChanged();
      } else {
        usersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public Builder addUsers(
        com.v2ray.core.common.protocol.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public Builder addUsers(
        int index, com.v2ray.core.common.protocol.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public Builder addAllUsers(
        java.lang.Iterable<? extends com.v2ray.core.common.protocol.User> values) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, users_);
        onChanged();
      } else {
        usersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public Builder clearUsers() {
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        usersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public Builder removeUsers(int index) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.remove(index);
        onChanged();
      } else {
        usersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public com.v2ray.core.common.protocol.User.Builder getUsersBuilder(
        int index) {
      return getUsersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public com.v2ray.core.common.protocol.UserOrBuilder getUsersOrBuilder(
        int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);  } else {
        return usersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public java.util.List<? extends com.v2ray.core.common.protocol.UserOrBuilder> 
         getUsersOrBuilderList() {
      if (usersBuilder_ != null) {
        return usersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(users_);
      }
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public com.v2ray.core.common.protocol.User.Builder addUsersBuilder() {
      return getUsersFieldBuilder().addBuilder(
          com.v2ray.core.common.protocol.User.getDefaultInstance());
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public com.v2ray.core.common.protocol.User.Builder addUsersBuilder(
        int index) {
      return getUsersFieldBuilder().addBuilder(
          index, com.v2ray.core.common.protocol.User.getDefaultInstance());
    }
    /**
     * <code>repeated .v2ray.core.common.protocol.User users = 1;</code>
     */
    public java.util.List<com.v2ray.core.common.protocol.User.Builder> 
         getUsersBuilderList() {
      return getUsersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.v2ray.core.common.protocol.User, com.v2ray.core.common.protocol.User.Builder, com.v2ray.core.common.protocol.UserOrBuilder> 
        getUsersFieldBuilder() {
      if (usersBuilder_ == null) {
        usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.v2ray.core.common.protocol.User, com.v2ray.core.common.protocol.User.Builder, com.v2ray.core.common.protocol.UserOrBuilder>(
                users_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        users_ = null;
      }
      return usersBuilder_;
    }

    private java.util.List<com.v2ray.core.proxy.trojan.Fallback> fallbacks_ =
      java.util.Collections.emptyList();
    private void ensureFallbacksIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        fallbacks_ = new java.util.ArrayList<com.v2ray.core.proxy.trojan.Fallback>(fallbacks_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.v2ray.core.proxy.trojan.Fallback, com.v2ray.core.proxy.trojan.Fallback.Builder, com.v2ray.core.proxy.trojan.FallbackOrBuilder> fallbacksBuilder_;

    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public java.util.List<com.v2ray.core.proxy.trojan.Fallback> getFallbacksList() {
      if (fallbacksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fallbacks_);
      } else {
        return fallbacksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public int getFallbacksCount() {
      if (fallbacksBuilder_ == null) {
        return fallbacks_.size();
      } else {
        return fallbacksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public com.v2ray.core.proxy.trojan.Fallback getFallbacks(int index) {
      if (fallbacksBuilder_ == null) {
        return fallbacks_.get(index);
      } else {
        return fallbacksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public Builder setFallbacks(
        int index, com.v2ray.core.proxy.trojan.Fallback value) {
      if (fallbacksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFallbacksIsMutable();
        fallbacks_.set(index, value);
        onChanged();
      } else {
        fallbacksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public Builder setFallbacks(
        int index, com.v2ray.core.proxy.trojan.Fallback.Builder builderForValue) {
      if (fallbacksBuilder_ == null) {
        ensureFallbacksIsMutable();
        fallbacks_.set(index, builderForValue.build());
        onChanged();
      } else {
        fallbacksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public Builder addFallbacks(com.v2ray.core.proxy.trojan.Fallback value) {
      if (fallbacksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFallbacksIsMutable();
        fallbacks_.add(value);
        onChanged();
      } else {
        fallbacksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public Builder addFallbacks(
        int index, com.v2ray.core.proxy.trojan.Fallback value) {
      if (fallbacksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFallbacksIsMutable();
        fallbacks_.add(index, value);
        onChanged();
      } else {
        fallbacksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public Builder addFallbacks(
        com.v2ray.core.proxy.trojan.Fallback.Builder builderForValue) {
      if (fallbacksBuilder_ == null) {
        ensureFallbacksIsMutable();
        fallbacks_.add(builderForValue.build());
        onChanged();
      } else {
        fallbacksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public Builder addFallbacks(
        int index, com.v2ray.core.proxy.trojan.Fallback.Builder builderForValue) {
      if (fallbacksBuilder_ == null) {
        ensureFallbacksIsMutable();
        fallbacks_.add(index, builderForValue.build());
        onChanged();
      } else {
        fallbacksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public Builder addAllFallbacks(
        java.lang.Iterable<? extends com.v2ray.core.proxy.trojan.Fallback> values) {
      if (fallbacksBuilder_ == null) {
        ensureFallbacksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fallbacks_);
        onChanged();
      } else {
        fallbacksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public Builder clearFallbacks() {
      if (fallbacksBuilder_ == null) {
        fallbacks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        fallbacksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public Builder removeFallbacks(int index) {
      if (fallbacksBuilder_ == null) {
        ensureFallbacksIsMutable();
        fallbacks_.remove(index);
        onChanged();
      } else {
        fallbacksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public com.v2ray.core.proxy.trojan.Fallback.Builder getFallbacksBuilder(
        int index) {
      return getFallbacksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public com.v2ray.core.proxy.trojan.FallbackOrBuilder getFallbacksOrBuilder(
        int index) {
      if (fallbacksBuilder_ == null) {
        return fallbacks_.get(index);  } else {
        return fallbacksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public java.util.List<? extends com.v2ray.core.proxy.trojan.FallbackOrBuilder> 
         getFallbacksOrBuilderList() {
      if (fallbacksBuilder_ != null) {
        return fallbacksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fallbacks_);
      }
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public com.v2ray.core.proxy.trojan.Fallback.Builder addFallbacksBuilder() {
      return getFallbacksFieldBuilder().addBuilder(
          com.v2ray.core.proxy.trojan.Fallback.getDefaultInstance());
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public com.v2ray.core.proxy.trojan.Fallback.Builder addFallbacksBuilder(
        int index) {
      return getFallbacksFieldBuilder().addBuilder(
          index, com.v2ray.core.proxy.trojan.Fallback.getDefaultInstance());
    }
    /**
     * <code>repeated .v2ray.core.proxy.trojan.Fallback fallbacks = 3;</code>
     */
    public java.util.List<com.v2ray.core.proxy.trojan.Fallback.Builder> 
         getFallbacksBuilderList() {
      return getFallbacksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.v2ray.core.proxy.trojan.Fallback, com.v2ray.core.proxy.trojan.Fallback.Builder, com.v2ray.core.proxy.trojan.FallbackOrBuilder> 
        getFallbacksFieldBuilder() {
      if (fallbacksBuilder_ == null) {
        fallbacksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.v2ray.core.proxy.trojan.Fallback, com.v2ray.core.proxy.trojan.Fallback.Builder, com.v2ray.core.proxy.trojan.FallbackOrBuilder>(
                fallbacks_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        fallbacks_ = null;
      }
      return fallbacksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.proxy.trojan.ServerConfig)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.proxy.trojan.ServerConfig)
  private static final com.v2ray.core.proxy.trojan.ServerConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.proxy.trojan.ServerConfig();
  }

  public static com.v2ray.core.proxy.trojan.ServerConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerConfig>
      PARSER = new com.google.protobuf.AbstractParser<ServerConfig>() {
    @java.lang.Override
    public ServerConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.v2ray.core.proxy.trojan.ServerConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

