// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/dns/fakedns/fakedns.proto

package com.v2ray.core.app.dns.fakedns;

public final class Fakedns {
  private Fakedns() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_dns_fakedns_FakeDnsPool_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_dns_fakedns_FakeDnsPool_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_dns_fakedns_FakeDnsPoolMulti_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_dns_fakedns_FakeDnsPoolMulti_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035app/dns/fakedns/fakedns.proto\022\032v2ray.c" +
      "ore.app.dns.fakedns\"/\n\013FakeDnsPool\022\017\n\007ip" +
      "_pool\030\001 \001(\t\022\017\n\007lruSize\030\002 \001(\003\"J\n\020FakeDnsP" +
      "oolMulti\0226\n\005pools\030\001 \003(\0132\'.v2ray.core.app" +
      ".dns.fakedns.FakeDnsPoolBo\n\036com.v2ray.co" +
      "re.app.dns.fakednsP\001Z.github.com/v2fly/v" +
      "2ray-core/v4/app/dns/fakedns\252\002\032V2Ray.Cor" +
      "e.App.Dns.Fakednsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_v2ray_core_app_dns_fakedns_FakeDnsPool_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v2ray_core_app_dns_fakedns_FakeDnsPool_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_dns_fakedns_FakeDnsPool_descriptor,
        new java.lang.String[] { "IpPool", "LruSize", });
    internal_static_v2ray_core_app_dns_fakedns_FakeDnsPoolMulti_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_v2ray_core_app_dns_fakedns_FakeDnsPoolMulti_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_dns_fakedns_FakeDnsPoolMulti_descriptor,
        new java.lang.String[] { "Pools", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
