// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/dns/fakedns/fakedns.proto

package com.v2ray.core.app.dns.fakedns;

public interface FakeDnsPoolMultiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.dns.fakedns.FakeDnsPoolMulti)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .v2ray.core.app.dns.fakedns.FakeDnsPool pools = 1;</code>
   */
  java.util.List<com.v2ray.core.app.dns.fakedns.FakeDnsPool> 
      getPoolsList();
  /**
   * <code>repeated .v2ray.core.app.dns.fakedns.FakeDnsPool pools = 1;</code>
   */
  com.v2ray.core.app.dns.fakedns.FakeDnsPool getPools(int index);
  /**
   * <code>repeated .v2ray.core.app.dns.fakedns.FakeDnsPool pools = 1;</code>
   */
  int getPoolsCount();
  /**
   * <code>repeated .v2ray.core.app.dns.fakedns.FakeDnsPool pools = 1;</code>
   */
  java.util.List<? extends com.v2ray.core.app.dns.fakedns.FakeDnsPoolOrBuilder> 
      getPoolsOrBuilderList();
  /**
   * <code>repeated .v2ray.core.app.dns.fakedns.FakeDnsPool pools = 1;</code>
   */
  com.v2ray.core.app.dns.fakedns.FakeDnsPoolOrBuilder getPoolsOrBuilder(
      int index);
}
