// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/config.proto

package com.v2ray.core.transport.internet;

public interface SocketConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.transport.internet.SocketConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Mark of the connection. If non-zero, the value will be set to SO_MARK.
   * </pre>
   *
   * <code>uint32 mark = 1;</code>
   * @return The mark.
   */
  int getMark();

  /**
   * <pre>
   * TFO is the state of TFO settings.
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
   * @return The enum numeric value on the wire for tfo.
   */
  int getTfoValue();
  /**
   * <pre>
   * TFO is the state of TFO settings.
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
   * @return The tfo.
   */
  com.v2ray.core.transport.internet.SocketConfig.TCPFastOpenState getTfo();

  /**
   * <pre>
   * TProxy is for enabling TProxy socket option.
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
   * @return The enum numeric value on the wire for tproxy.
   */
  int getTproxyValue();
  /**
   * <pre>
   * TProxy is for enabling TProxy socket option.
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
   * @return The tproxy.
   */
  com.v2ray.core.transport.internet.SocketConfig.TProxyMode getTproxy();

  /**
   * <pre>
   * ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
   * option. This option is for UDP only.
   * </pre>
   *
   * <code>bool receive_original_dest_address = 4;</code>
   * @return The receiveOriginalDestAddress.
   */
  boolean getReceiveOriginalDestAddress();

  /**
   * <code>bytes bind_address = 5;</code>
   * @return The bindAddress.
   */
  com.google.protobuf.ByteString getBindAddress();

  /**
   * <code>uint32 bind_port = 6;</code>
   * @return The bindPort.
   */
  int getBindPort();

  /**
   * <code>bool accept_proxy_protocol = 7;</code>
   * @return The acceptProxyProtocol.
   */
  boolean getAcceptProxyProtocol();

  /**
   * <code>int32 tcp_keep_alive_interval = 8;</code>
   * @return The tcpKeepAliveInterval.
   */
  int getTcpKeepAliveInterval();

  /**
   * <code>uint32 tfo_queue_length = 9;</code>
   * @return The tfoQueueLength.
   */
  int getTfoQueueLength();

  /**
   * <code>int32 tcp_keep_alive_idle = 10;</code>
   * @return The tcpKeepAliveIdle.
   */
  int getTcpKeepAliveIdle();
}
