// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport/internet/config.proto

package com.v2ray.core.transport.internet;

public interface TransportConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.transport.internet.TransportConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Type of network that this settings supports.
   * Deprecated. Use the string form below.
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.TransportProtocol protocol = 1 [deprecated = true];</code>
   * @deprecated v2ray.core.transport.internet.TransportConfig.protocol is deprecated.
   *     See transport/internet/config.proto;l=22
   * @return The enum numeric value on the wire for protocol.
   */
  @java.lang.Deprecated int getProtocolValue();
  /**
   * <pre>
   * Type of network that this settings supports.
   * Deprecated. Use the string form below.
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.TransportProtocol protocol = 1 [deprecated = true];</code>
   * @deprecated v2ray.core.transport.internet.TransportConfig.protocol is deprecated.
   *     See transport/internet/config.proto;l=22
   * @return The protocol.
   */
  @java.lang.Deprecated com.v2ray.core.transport.internet.TransportProtocol getProtocol();

  /**
   * <pre>
   * Type of network that this settings supports.
   * </pre>
   *
   * <code>string protocol_name = 3;</code>
   * @return The protocolName.
   */
  java.lang.String getProtocolName();
  /**
   * <pre>
   * Type of network that this settings supports.
   * </pre>
   *
   * <code>string protocol_name = 3;</code>
   * @return The bytes for protocolName.
   */
  com.google.protobuf.ByteString
      getProtocolNameBytes();

  /**
   * <pre>
   * Specific settings. Must be of the transports.
   * </pre>
   *
   * <code>.v2ray.core.common.serial.TypedMessage settings = 2;</code>
   * @return Whether the settings field is set.
   */
  boolean hasSettings();
  /**
   * <pre>
   * Specific settings. Must be of the transports.
   * </pre>
   *
   * <code>.v2ray.core.common.serial.TypedMessage settings = 2;</code>
   * @return The settings.
   */
  com.v2ray.core.common.serial.TypedMessage getSettings();
  /**
   * <pre>
   * Specific settings. Must be of the transports.
   * </pre>
   *
   * <code>.v2ray.core.common.serial.TypedMessage settings = 2;</code>
   */
  com.v2ray.core.common.serial.TypedMessageOrBuilder getSettingsOrBuilder();
}
