// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/router/command/command.proto

package com.v2ray.core.app.router.command;

/**
 * <pre>
 * RoutingContext is the context with information relative to routing process.
 * It conforms to the structure of v2ray.core.features.routing.Context and
 * v2ray.core.features.routing.Route.
 * </pre>
 *
 * Protobuf type {@code v2ray.core.app.router.command.RoutingContext}
 */
public final class RoutingContext extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.app.router.command.RoutingContext)
    RoutingContextOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RoutingContext.newBuilder() to construct.
  private RoutingContext(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RoutingContext() {
    inboundTag_ = "";
    network_ = 0;
    sourceIPs_ = java.util.Collections.emptyList();
    targetIPs_ = java.util.Collections.emptyList();
    targetDomain_ = "";
    protocol_ = "";
    user_ = "";
    outboundGroupTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    outboundTag_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RoutingContext();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.app.router.command.Command.internal_static_v2ray_core_app_router_command_RoutingContext_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 10:
        return internalGetAttributes();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.app.router.command.Command.internal_static_v2ray_core_app_router_command_RoutingContext_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.app.router.command.RoutingContext.class, com.v2ray.core.app.router.command.RoutingContext.Builder.class);
  }

  public static final int INBOUNDTAG_FIELD_NUMBER = 1;
  private volatile java.lang.Object inboundTag_;
  /**
   * <code>string InboundTag = 1;</code>
   * @return The inboundTag.
   */
  @java.lang.Override
  public java.lang.String getInboundTag() {
    java.lang.Object ref = inboundTag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inboundTag_ = s;
      return s;
    }
  }
  /**
   * <code>string InboundTag = 1;</code>
   * @return The bytes for inboundTag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInboundTagBytes() {
    java.lang.Object ref = inboundTag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inboundTag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NETWORK_FIELD_NUMBER = 2;
  private int network_;
  /**
   * <code>.v2ray.core.common.net.Network Network = 2;</code>
   * @return The enum numeric value on the wire for network.
   */
  @java.lang.Override public int getNetworkValue() {
    return network_;
  }
  /**
   * <code>.v2ray.core.common.net.Network Network = 2;</code>
   * @return The network.
   */
  @java.lang.Override public com.v2ray.core.common.net.Network getNetwork() {
    @SuppressWarnings("deprecation")
    com.v2ray.core.common.net.Network result = com.v2ray.core.common.net.Network.valueOf(network_);
    return result == null ? com.v2ray.core.common.net.Network.UNRECOGNIZED : result;
  }

  public static final int SOURCEIPS_FIELD_NUMBER = 3;
  private java.util.List<com.google.protobuf.ByteString> sourceIPs_;
  /**
   * <code>repeated bytes SourceIPs = 3;</code>
   * @return A list containing the sourceIPs.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getSourceIPsList() {
    return sourceIPs_;
  }
  /**
   * <code>repeated bytes SourceIPs = 3;</code>
   * @return The count of sourceIPs.
   */
  public int getSourceIPsCount() {
    return sourceIPs_.size();
  }
  /**
   * <code>repeated bytes SourceIPs = 3;</code>
   * @param index The index of the element to return.
   * @return The sourceIPs at the given index.
   */
  public com.google.protobuf.ByteString getSourceIPs(int index) {
    return sourceIPs_.get(index);
  }

  public static final int TARGETIPS_FIELD_NUMBER = 4;
  private java.util.List<com.google.protobuf.ByteString> targetIPs_;
  /**
   * <code>repeated bytes TargetIPs = 4;</code>
   * @return A list containing the targetIPs.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getTargetIPsList() {
    return targetIPs_;
  }
  /**
   * <code>repeated bytes TargetIPs = 4;</code>
   * @return The count of targetIPs.
   */
  public int getTargetIPsCount() {
    return targetIPs_.size();
  }
  /**
   * <code>repeated bytes TargetIPs = 4;</code>
   * @param index The index of the element to return.
   * @return The targetIPs at the given index.
   */
  public com.google.protobuf.ByteString getTargetIPs(int index) {
    return targetIPs_.get(index);
  }

  public static final int SOURCEPORT_FIELD_NUMBER = 5;
  private int sourcePort_;
  /**
   * <code>uint32 SourcePort = 5;</code>
   * @return The sourcePort.
   */
  @java.lang.Override
  public int getSourcePort() {
    return sourcePort_;
  }

  public static final int TARGETPORT_FIELD_NUMBER = 6;
  private int targetPort_;
  /**
   * <code>uint32 TargetPort = 6;</code>
   * @return The targetPort.
   */
  @java.lang.Override
  public int getTargetPort() {
    return targetPort_;
  }

  public static final int TARGETDOMAIN_FIELD_NUMBER = 7;
  private volatile java.lang.Object targetDomain_;
  /**
   * <code>string TargetDomain = 7;</code>
   * @return The targetDomain.
   */
  @java.lang.Override
  public java.lang.String getTargetDomain() {
    java.lang.Object ref = targetDomain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetDomain_ = s;
      return s;
    }
  }
  /**
   * <code>string TargetDomain = 7;</code>
   * @return The bytes for targetDomain.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetDomainBytes() {
    java.lang.Object ref = targetDomain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetDomain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROTOCOL_FIELD_NUMBER = 8;
  private volatile java.lang.Object protocol_;
  /**
   * <code>string Protocol = 8;</code>
   * @return The protocol.
   */
  @java.lang.Override
  public java.lang.String getProtocol() {
    java.lang.Object ref = protocol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      protocol_ = s;
      return s;
    }
  }
  /**
   * <code>string Protocol = 8;</code>
   * @return The bytes for protocol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProtocolBytes() {
    java.lang.Object ref = protocol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      protocol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_FIELD_NUMBER = 9;
  private volatile java.lang.Object user_;
  /**
   * <code>string User = 9;</code>
   * @return The user.
   */
  @java.lang.Override
  public java.lang.String getUser() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      user_ = s;
      return s;
    }
  }
  /**
   * <code>string User = 9;</code>
   * @return The bytes for user.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserBytes() {
    java.lang.Object ref = user_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      user_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 10;
  private static final class AttributesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.v2ray.core.app.router.command.Command.internal_static_v2ray_core_app_router_command_RoutingContext_AttributesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> attributes_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetAttributes() {
    if (attributes_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AttributesDefaultEntryHolder.defaultEntry);
    }
    return attributes_;
  }

  public int getAttributesCount() {
    return internalGetAttributes().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; Attributes = 10;</code>
   */

  @java.lang.Override
  public boolean containsAttributes(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetAttributes().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
    return getAttributesMap();
  }
  /**
   * <code>map&lt;string, string&gt; Attributes = 10;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
    return internalGetAttributes().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; Attributes = 10;</code>
   */
  @java.lang.Override

  public java.lang.String getAttributesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; Attributes = 10;</code>
   */
  @java.lang.Override

  public java.lang.String getAttributesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int OUTBOUNDGROUPTAGS_FIELD_NUMBER = 11;
  private com.google.protobuf.LazyStringList outboundGroupTags_;
  /**
   * <code>repeated string OutboundGroupTags = 11;</code>
   * @return A list containing the outboundGroupTags.
   */
  public com.google.protobuf.ProtocolStringList
      getOutboundGroupTagsList() {
    return outboundGroupTags_;
  }
  /**
   * <code>repeated string OutboundGroupTags = 11;</code>
   * @return The count of outboundGroupTags.
   */
  public int getOutboundGroupTagsCount() {
    return outboundGroupTags_.size();
  }
  /**
   * <code>repeated string OutboundGroupTags = 11;</code>
   * @param index The index of the element to return.
   * @return The outboundGroupTags at the given index.
   */
  public java.lang.String getOutboundGroupTags(int index) {
    return outboundGroupTags_.get(index);
  }
  /**
   * <code>repeated string OutboundGroupTags = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the outboundGroupTags at the given index.
   */
  public com.google.protobuf.ByteString
      getOutboundGroupTagsBytes(int index) {
    return outboundGroupTags_.getByteString(index);
  }

  public static final int OUTBOUNDTAG_FIELD_NUMBER = 12;
  private volatile java.lang.Object outboundTag_;
  /**
   * <code>string OutboundTag = 12;</code>
   * @return The outboundTag.
   */
  @java.lang.Override
  public java.lang.String getOutboundTag() {
    java.lang.Object ref = outboundTag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outboundTag_ = s;
      return s;
    }
  }
  /**
   * <code>string OutboundTag = 12;</code>
   * @return The bytes for outboundTag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOutboundTagBytes() {
    java.lang.Object ref = outboundTag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outboundTag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(inboundTag_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, inboundTag_);
    }
    if (network_ != com.v2ray.core.common.net.Network.Unknown.getNumber()) {
      output.writeEnum(2, network_);
    }
    for (int i = 0; i < sourceIPs_.size(); i++) {
      output.writeBytes(3, sourceIPs_.get(i));
    }
    for (int i = 0; i < targetIPs_.size(); i++) {
      output.writeBytes(4, targetIPs_.get(i));
    }
    if (sourcePort_ != 0) {
      output.writeUInt32(5, sourcePort_);
    }
    if (targetPort_ != 0) {
      output.writeUInt32(6, targetPort_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetDomain_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, targetDomain_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(protocol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, protocol_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(user_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, user_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAttributes(),
        AttributesDefaultEntryHolder.defaultEntry,
        10);
    for (int i = 0; i < outboundGroupTags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, outboundGroupTags_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(outboundTag_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, outboundTag_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(inboundTag_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, inboundTag_);
    }
    if (network_ != com.v2ray.core.common.net.Network.Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, network_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < sourceIPs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(sourceIPs_.get(i));
      }
      size += dataSize;
      size += 1 * getSourceIPsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < targetIPs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(targetIPs_.get(i));
      }
      size += dataSize;
      size += 1 * getTargetIPsList().size();
    }
    if (sourcePort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, sourcePort_);
    }
    if (targetPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, targetPort_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetDomain_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, targetDomain_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(protocol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, protocol_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(user_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, user_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetAttributes().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, attributes__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < outboundGroupTags_.size(); i++) {
        dataSize += computeStringSizeNoTag(outboundGroupTags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOutboundGroupTagsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(outboundTag_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, outboundTag_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.app.router.command.RoutingContext)) {
      return super.equals(obj);
    }
    com.v2ray.core.app.router.command.RoutingContext other = (com.v2ray.core.app.router.command.RoutingContext) obj;

    if (!getInboundTag()
        .equals(other.getInboundTag())) return false;
    if (network_ != other.network_) return false;
    if (!getSourceIPsList()
        .equals(other.getSourceIPsList())) return false;
    if (!getTargetIPsList()
        .equals(other.getTargetIPsList())) return false;
    if (getSourcePort()
        != other.getSourcePort()) return false;
    if (getTargetPort()
        != other.getTargetPort()) return false;
    if (!getTargetDomain()
        .equals(other.getTargetDomain())) return false;
    if (!getProtocol()
        .equals(other.getProtocol())) return false;
    if (!getUser()
        .equals(other.getUser())) return false;
    if (!internalGetAttributes().equals(
        other.internalGetAttributes())) return false;
    if (!getOutboundGroupTagsList()
        .equals(other.getOutboundGroupTagsList())) return false;
    if (!getOutboundTag()
        .equals(other.getOutboundTag())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INBOUNDTAG_FIELD_NUMBER;
    hash = (53 * hash) + getInboundTag().hashCode();
    hash = (37 * hash) + NETWORK_FIELD_NUMBER;
    hash = (53 * hash) + network_;
    if (getSourceIPsCount() > 0) {
      hash = (37 * hash) + SOURCEIPS_FIELD_NUMBER;
      hash = (53 * hash) + getSourceIPsList().hashCode();
    }
    if (getTargetIPsCount() > 0) {
      hash = (37 * hash) + TARGETIPS_FIELD_NUMBER;
      hash = (53 * hash) + getTargetIPsList().hashCode();
    }
    hash = (37 * hash) + SOURCEPORT_FIELD_NUMBER;
    hash = (53 * hash) + getSourcePort();
    hash = (37 * hash) + TARGETPORT_FIELD_NUMBER;
    hash = (53 * hash) + getTargetPort();
    hash = (37 * hash) + TARGETDOMAIN_FIELD_NUMBER;
    hash = (53 * hash) + getTargetDomain().hashCode();
    hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + getProtocol().hashCode();
    hash = (37 * hash) + USER_FIELD_NUMBER;
    hash = (53 * hash) + getUser().hashCode();
    if (!internalGetAttributes().getMap().isEmpty()) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAttributes().hashCode();
    }
    if (getOutboundGroupTagsCount() > 0) {
      hash = (37 * hash) + OUTBOUNDGROUPTAGS_FIELD_NUMBER;
      hash = (53 * hash) + getOutboundGroupTagsList().hashCode();
    }
    hash = (37 * hash) + OUTBOUNDTAG_FIELD_NUMBER;
    hash = (53 * hash) + getOutboundTag().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.app.router.command.RoutingContext parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.command.RoutingContext parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.command.RoutingContext parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.command.RoutingContext parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.command.RoutingContext parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.app.router.command.RoutingContext parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.app.router.command.RoutingContext parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.command.RoutingContext parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.router.command.RoutingContext parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.command.RoutingContext parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.app.router.command.RoutingContext parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.app.router.command.RoutingContext parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.app.router.command.RoutingContext prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RoutingContext is the context with information relative to routing process.
   * It conforms to the structure of v2ray.core.features.routing.Context and
   * v2ray.core.features.routing.Route.
   * </pre>
   *
   * Protobuf type {@code v2ray.core.app.router.command.RoutingContext}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.app.router.command.RoutingContext)
      com.v2ray.core.app.router.command.RoutingContextOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.app.router.command.Command.internal_static_v2ray_core_app_router_command_RoutingContext_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 10:
          return internalGetAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 10:
          return internalGetMutableAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.app.router.command.Command.internal_static_v2ray_core_app_router_command_RoutingContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.app.router.command.RoutingContext.class, com.v2ray.core.app.router.command.RoutingContext.Builder.class);
    }

    // Construct using com.v2ray.core.app.router.command.RoutingContext.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      inboundTag_ = "";

      network_ = 0;

      sourceIPs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      targetIPs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      sourcePort_ = 0;

      targetPort_ = 0;

      targetDomain_ = "";

      protocol_ = "";

      user_ = "";

      internalGetMutableAttributes().clear();
      outboundGroupTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      outboundTag_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.app.router.command.Command.internal_static_v2ray_core_app_router_command_RoutingContext_descriptor;
    }

    @java.lang.Override
    public com.v2ray.core.app.router.command.RoutingContext getDefaultInstanceForType() {
      return com.v2ray.core.app.router.command.RoutingContext.getDefaultInstance();
    }

    @java.lang.Override
    public com.v2ray.core.app.router.command.RoutingContext build() {
      com.v2ray.core.app.router.command.RoutingContext result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.v2ray.core.app.router.command.RoutingContext buildPartial() {
      com.v2ray.core.app.router.command.RoutingContext result = new com.v2ray.core.app.router.command.RoutingContext(this);
      int from_bitField0_ = bitField0_;
      result.inboundTag_ = inboundTag_;
      result.network_ = network_;
      if (((bitField0_ & 0x00000001) != 0)) {
        sourceIPs_ = java.util.Collections.unmodifiableList(sourceIPs_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.sourceIPs_ = sourceIPs_;
      if (((bitField0_ & 0x00000002) != 0)) {
        targetIPs_ = java.util.Collections.unmodifiableList(targetIPs_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.targetIPs_ = targetIPs_;
      result.sourcePort_ = sourcePort_;
      result.targetPort_ = targetPort_;
      result.targetDomain_ = targetDomain_;
      result.protocol_ = protocol_;
      result.user_ = user_;
      result.attributes_ = internalGetAttributes();
      result.attributes_.makeImmutable();
      if (((bitField0_ & 0x00000008) != 0)) {
        outboundGroupTags_ = outboundGroupTags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.outboundGroupTags_ = outboundGroupTags_;
      result.outboundTag_ = outboundTag_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.app.router.command.RoutingContext) {
        return mergeFrom((com.v2ray.core.app.router.command.RoutingContext)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.app.router.command.RoutingContext other) {
      if (other == com.v2ray.core.app.router.command.RoutingContext.getDefaultInstance()) return this;
      if (!other.getInboundTag().isEmpty()) {
        inboundTag_ = other.inboundTag_;
        onChanged();
      }
      if (other.network_ != 0) {
        setNetworkValue(other.getNetworkValue());
      }
      if (!other.sourceIPs_.isEmpty()) {
        if (sourceIPs_.isEmpty()) {
          sourceIPs_ = other.sourceIPs_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSourceIPsIsMutable();
          sourceIPs_.addAll(other.sourceIPs_);
        }
        onChanged();
      }
      if (!other.targetIPs_.isEmpty()) {
        if (targetIPs_.isEmpty()) {
          targetIPs_ = other.targetIPs_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureTargetIPsIsMutable();
          targetIPs_.addAll(other.targetIPs_);
        }
        onChanged();
      }
      if (other.getSourcePort() != 0) {
        setSourcePort(other.getSourcePort());
      }
      if (other.getTargetPort() != 0) {
        setTargetPort(other.getTargetPort());
      }
      if (!other.getTargetDomain().isEmpty()) {
        targetDomain_ = other.targetDomain_;
        onChanged();
      }
      if (!other.getProtocol().isEmpty()) {
        protocol_ = other.protocol_;
        onChanged();
      }
      if (!other.getUser().isEmpty()) {
        user_ = other.user_;
        onChanged();
      }
      internalGetMutableAttributes().mergeFrom(
          other.internalGetAttributes());
      if (!other.outboundGroupTags_.isEmpty()) {
        if (outboundGroupTags_.isEmpty()) {
          outboundGroupTags_ = other.outboundGroupTags_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureOutboundGroupTagsIsMutable();
          outboundGroupTags_.addAll(other.outboundGroupTags_);
        }
        onChanged();
      }
      if (!other.getOutboundTag().isEmpty()) {
        outboundTag_ = other.outboundTag_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              inboundTag_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              network_ = input.readEnum();

              break;
            } // case 16
            case 26: {
              com.google.protobuf.ByteString v = input.readBytes();
              ensureSourceIPsIsMutable();
              sourceIPs_.add(v);
              break;
            } // case 26
            case 34: {
              com.google.protobuf.ByteString v = input.readBytes();
              ensureTargetIPsIsMutable();
              targetIPs_.add(v);
              break;
            } // case 34
            case 40: {
              sourcePort_ = input.readUInt32();

              break;
            } // case 40
            case 48: {
              targetPort_ = input.readUInt32();

              break;
            } // case 48
            case 58: {
              targetDomain_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 66: {
              protocol_ = input.readStringRequireUtf8();

              break;
            } // case 66
            case 74: {
              user_ = input.readStringRequireUtf8();

              break;
            } // case 74
            case 82: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              attributes__ = input.readMessage(
                  AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableAttributes().getMutableMap().put(
                  attributes__.getKey(), attributes__.getValue());
              break;
            } // case 82
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureOutboundGroupTagsIsMutable();
              outboundGroupTags_.add(s);
              break;
            } // case 90
            case 98: {
              outboundTag_ = input.readStringRequireUtf8();

              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object inboundTag_ = "";
    /**
     * <code>string InboundTag = 1;</code>
     * @return The inboundTag.
     */
    public java.lang.String getInboundTag() {
      java.lang.Object ref = inboundTag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inboundTag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string InboundTag = 1;</code>
     * @return The bytes for inboundTag.
     */
    public com.google.protobuf.ByteString
        getInboundTagBytes() {
      java.lang.Object ref = inboundTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inboundTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string InboundTag = 1;</code>
     * @param value The inboundTag to set.
     * @return This builder for chaining.
     */
    public Builder setInboundTag(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inboundTag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string InboundTag = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInboundTag() {
      
      inboundTag_ = getDefaultInstance().getInboundTag();
      onChanged();
      return this;
    }
    /**
     * <code>string InboundTag = 1;</code>
     * @param value The bytes for inboundTag to set.
     * @return This builder for chaining.
     */
    public Builder setInboundTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inboundTag_ = value;
      onChanged();
      return this;
    }

    private int network_ = 0;
    /**
     * <code>.v2ray.core.common.net.Network Network = 2;</code>
     * @return The enum numeric value on the wire for network.
     */
    @java.lang.Override public int getNetworkValue() {
      return network_;
    }
    /**
     * <code>.v2ray.core.common.net.Network Network = 2;</code>
     * @param value The enum numeric value on the wire for network to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkValue(int value) {
      
      network_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.v2ray.core.common.net.Network Network = 2;</code>
     * @return The network.
     */
    @java.lang.Override
    public com.v2ray.core.common.net.Network getNetwork() {
      @SuppressWarnings("deprecation")
      com.v2ray.core.common.net.Network result = com.v2ray.core.common.net.Network.valueOf(network_);
      return result == null ? com.v2ray.core.common.net.Network.UNRECOGNIZED : result;
    }
    /**
     * <code>.v2ray.core.common.net.Network Network = 2;</code>
     * @param value The network to set.
     * @return This builder for chaining.
     */
    public Builder setNetwork(com.v2ray.core.common.net.Network value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      network_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.v2ray.core.common.net.Network Network = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetwork() {
      
      network_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> sourceIPs_ = java.util.Collections.emptyList();
    private void ensureSourceIPsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        sourceIPs_ = new java.util.ArrayList<com.google.protobuf.ByteString>(sourceIPs_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated bytes SourceIPs = 3;</code>
     * @return A list containing the sourceIPs.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getSourceIPsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(sourceIPs_) : sourceIPs_;
    }
    /**
     * <code>repeated bytes SourceIPs = 3;</code>
     * @return The count of sourceIPs.
     */
    public int getSourceIPsCount() {
      return sourceIPs_.size();
    }
    /**
     * <code>repeated bytes SourceIPs = 3;</code>
     * @param index The index of the element to return.
     * @return The sourceIPs at the given index.
     */
    public com.google.protobuf.ByteString getSourceIPs(int index) {
      return sourceIPs_.get(index);
    }
    /**
     * <code>repeated bytes SourceIPs = 3;</code>
     * @param index The index to set the value at.
     * @param value The sourceIPs to set.
     * @return This builder for chaining.
     */
    public Builder setSourceIPs(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSourceIPsIsMutable();
      sourceIPs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes SourceIPs = 3;</code>
     * @param value The sourceIPs to add.
     * @return This builder for chaining.
     */
    public Builder addSourceIPs(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSourceIPsIsMutable();
      sourceIPs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes SourceIPs = 3;</code>
     * @param values The sourceIPs to add.
     * @return This builder for chaining.
     */
    public Builder addAllSourceIPs(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureSourceIPsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, sourceIPs_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes SourceIPs = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceIPs() {
      sourceIPs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.ByteString> targetIPs_ = java.util.Collections.emptyList();
    private void ensureTargetIPsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        targetIPs_ = new java.util.ArrayList<com.google.protobuf.ByteString>(targetIPs_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated bytes TargetIPs = 4;</code>
     * @return A list containing the targetIPs.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getTargetIPsList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(targetIPs_) : targetIPs_;
    }
    /**
     * <code>repeated bytes TargetIPs = 4;</code>
     * @return The count of targetIPs.
     */
    public int getTargetIPsCount() {
      return targetIPs_.size();
    }
    /**
     * <code>repeated bytes TargetIPs = 4;</code>
     * @param index The index of the element to return.
     * @return The targetIPs at the given index.
     */
    public com.google.protobuf.ByteString getTargetIPs(int index) {
      return targetIPs_.get(index);
    }
    /**
     * <code>repeated bytes TargetIPs = 4;</code>
     * @param index The index to set the value at.
     * @param value The targetIPs to set.
     * @return This builder for chaining.
     */
    public Builder setTargetIPs(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetIPsIsMutable();
      targetIPs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes TargetIPs = 4;</code>
     * @param value The targetIPs to add.
     * @return This builder for chaining.
     */
    public Builder addTargetIPs(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetIPsIsMutable();
      targetIPs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes TargetIPs = 4;</code>
     * @param values The targetIPs to add.
     * @return This builder for chaining.
     */
    public Builder addAllTargetIPs(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureTargetIPsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, targetIPs_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes TargetIPs = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetIPs() {
      targetIPs_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private int sourcePort_ ;
    /**
     * <code>uint32 SourcePort = 5;</code>
     * @return The sourcePort.
     */
    @java.lang.Override
    public int getSourcePort() {
      return sourcePort_;
    }
    /**
     * <code>uint32 SourcePort = 5;</code>
     * @param value The sourcePort to set.
     * @return This builder for chaining.
     */
    public Builder setSourcePort(int value) {
      
      sourcePort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 SourcePort = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourcePort() {
      
      sourcePort_ = 0;
      onChanged();
      return this;
    }

    private int targetPort_ ;
    /**
     * <code>uint32 TargetPort = 6;</code>
     * @return The targetPort.
     */
    @java.lang.Override
    public int getTargetPort() {
      return targetPort_;
    }
    /**
     * <code>uint32 TargetPort = 6;</code>
     * @param value The targetPort to set.
     * @return This builder for chaining.
     */
    public Builder setTargetPort(int value) {
      
      targetPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 TargetPort = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetPort() {
      
      targetPort_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object targetDomain_ = "";
    /**
     * <code>string TargetDomain = 7;</code>
     * @return The targetDomain.
     */
    public java.lang.String getTargetDomain() {
      java.lang.Object ref = targetDomain_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetDomain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string TargetDomain = 7;</code>
     * @return The bytes for targetDomain.
     */
    public com.google.protobuf.ByteString
        getTargetDomainBytes() {
      java.lang.Object ref = targetDomain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetDomain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string TargetDomain = 7;</code>
     * @param value The targetDomain to set.
     * @return This builder for chaining.
     */
    public Builder setTargetDomain(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetDomain_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string TargetDomain = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetDomain() {
      
      targetDomain_ = getDefaultInstance().getTargetDomain();
      onChanged();
      return this;
    }
    /**
     * <code>string TargetDomain = 7;</code>
     * @param value The bytes for targetDomain to set.
     * @return This builder for chaining.
     */
    public Builder setTargetDomainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetDomain_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object protocol_ = "";
    /**
     * <code>string Protocol = 8;</code>
     * @return The protocol.
     */
    public java.lang.String getProtocol() {
      java.lang.Object ref = protocol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Protocol = 8;</code>
     * @return The bytes for protocol.
     */
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      java.lang.Object ref = protocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Protocol = 8;</code>
     * @param value The protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protocol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Protocol = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocol() {
      
      protocol_ = getDefaultInstance().getProtocol();
      onChanged();
      return this;
    }
    /**
     * <code>string Protocol = 8;</code>
     * @param value The bytes for protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      protocol_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object user_ = "";
    /**
     * <code>string User = 9;</code>
     * @return The user.
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string User = 9;</code>
     * @return The bytes for user.
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string User = 9;</code>
     * @param value The user to set.
     * @return This builder for chaining.
     */
    public Builder setUser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      user_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string User = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUser() {
      
      user_ = getDefaultInstance().getUser();
      onChanged();
      return this;
    }
    /**
     * <code>string User = 9;</code>
     * @param value The bytes for user to set.
     * @return This builder for chaining.
     */
    public Builder setUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      user_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> attributes_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAttributes() {
      if (attributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableAttributes() {
      onChanged();;
      if (attributes_ == null) {
        attributes_ = com.google.protobuf.MapField.newMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      if (!attributes_.isMutable()) {
        attributes_ = attributes_.copy();
      }
      return attributes_;
    }

    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; Attributes = 10;</code>
     */

    @java.lang.Override
    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;string, string&gt; Attributes = 10;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; Attributes = 10;</code>
     */
    @java.lang.Override

    public java.lang.String getAttributesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; Attributes = 10;</code>
     */
    @java.lang.Override

    public java.lang.String getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAttributes() {
      internalGetMutableAttributes().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; Attributes = 10;</code>
     */

    public Builder removeAttributes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableAttributes().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableAttributes() {
      return internalGetMutableAttributes().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; Attributes = 10;</code>
     */
    public Builder putAttributes(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableAttributes().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; Attributes = 10;</code>
     */

    public Builder putAllAttributes(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableAttributes().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.LazyStringList outboundGroupTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureOutboundGroupTagsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        outboundGroupTags_ = new com.google.protobuf.LazyStringArrayList(outboundGroupTags_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated string OutboundGroupTags = 11;</code>
     * @return A list containing the outboundGroupTags.
     */
    public com.google.protobuf.ProtocolStringList
        getOutboundGroupTagsList() {
      return outboundGroupTags_.getUnmodifiableView();
    }
    /**
     * <code>repeated string OutboundGroupTags = 11;</code>
     * @return The count of outboundGroupTags.
     */
    public int getOutboundGroupTagsCount() {
      return outboundGroupTags_.size();
    }
    /**
     * <code>repeated string OutboundGroupTags = 11;</code>
     * @param index The index of the element to return.
     * @return The outboundGroupTags at the given index.
     */
    public java.lang.String getOutboundGroupTags(int index) {
      return outboundGroupTags_.get(index);
    }
    /**
     * <code>repeated string OutboundGroupTags = 11;</code>
     * @param index The index of the value to return.
     * @return The bytes of the outboundGroupTags at the given index.
     */
    public com.google.protobuf.ByteString
        getOutboundGroupTagsBytes(int index) {
      return outboundGroupTags_.getByteString(index);
    }
    /**
     * <code>repeated string OutboundGroupTags = 11;</code>
     * @param index The index to set the value at.
     * @param value The outboundGroupTags to set.
     * @return This builder for chaining.
     */
    public Builder setOutboundGroupTags(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOutboundGroupTagsIsMutable();
      outboundGroupTags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string OutboundGroupTags = 11;</code>
     * @param value The outboundGroupTags to add.
     * @return This builder for chaining.
     */
    public Builder addOutboundGroupTags(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOutboundGroupTagsIsMutable();
      outboundGroupTags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string OutboundGroupTags = 11;</code>
     * @param values The outboundGroupTags to add.
     * @return This builder for chaining.
     */
    public Builder addAllOutboundGroupTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureOutboundGroupTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, outboundGroupTags_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string OutboundGroupTags = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutboundGroupTags() {
      outboundGroupTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string OutboundGroupTags = 11;</code>
     * @param value The bytes of the outboundGroupTags to add.
     * @return This builder for chaining.
     */
    public Builder addOutboundGroupTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureOutboundGroupTagsIsMutable();
      outboundGroupTags_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object outboundTag_ = "";
    /**
     * <code>string OutboundTag = 12;</code>
     * @return The outboundTag.
     */
    public java.lang.String getOutboundTag() {
      java.lang.Object ref = outboundTag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outboundTag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string OutboundTag = 12;</code>
     * @return The bytes for outboundTag.
     */
    public com.google.protobuf.ByteString
        getOutboundTagBytes() {
      java.lang.Object ref = outboundTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outboundTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string OutboundTag = 12;</code>
     * @param value The outboundTag to set.
     * @return This builder for chaining.
     */
    public Builder setOutboundTag(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      outboundTag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string OutboundTag = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutboundTag() {
      
      outboundTag_ = getDefaultInstance().getOutboundTag();
      onChanged();
      return this;
    }
    /**
     * <code>string OutboundTag = 12;</code>
     * @param value The bytes for outboundTag to set.
     * @return This builder for chaining.
     */
    public Builder setOutboundTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      outboundTag_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.app.router.command.RoutingContext)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.app.router.command.RoutingContext)
  private static final com.v2ray.core.app.router.command.RoutingContext DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.app.router.command.RoutingContext();
  }

  public static com.v2ray.core.app.router.command.RoutingContext getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RoutingContext>
      PARSER = new com.google.protobuf.AbstractParser<RoutingContext>() {
    @java.lang.Override
    public RoutingContext parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RoutingContext> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RoutingContext> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.v2ray.core.app.router.command.RoutingContext getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

