// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

package com.v2ray.core.app.stats.command;

public interface QueryStatsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.stats.command.QueryStatsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pattern = 1;</code>
   * @return The pattern.
   */
  java.lang.String getPattern();
  /**
   * <code>string pattern = 1;</code>
   * @return The bytes for pattern.
   */
  com.google.protobuf.ByteString
      getPatternBytes();

  /**
   * <code>bool reset = 2;</code>
   * @return The reset.
   */
  boolean getReset();
}
