// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/stats/command/command.proto

package com.v2ray.core.app.stats.command;

public interface SysStatsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.stats.command.SysStatsRequest)
    com.google.protobuf.MessageOrBuilder {
}
