// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/freedom/config.proto

package com.v2ray.core.proxy.freedom;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.proxy.freedom.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.v2ray.core.proxy.freedom.Config.DomainStrategy domain_strategy = 1;</code>
   * @return The enum numeric value on the wire for domainStrategy.
   */
  int getDomainStrategyValue();
  /**
   * <code>.v2ray.core.proxy.freedom.Config.DomainStrategy domain_strategy = 1;</code>
   * @return The domainStrategy.
   */
  com.v2ray.core.proxy.freedom.Config.DomainStrategy getDomainStrategy();

  /**
   * <code>uint32 timeout = 2 [deprecated = true];</code>
   * @deprecated v2ray.core.proxy.freedom.Config.timeout is deprecated.
   *     See proxy/freedom/config.proto;l=22
   * @return The timeout.
   */
  @java.lang.Deprecated int getTimeout();

  /**
   * <code>.v2ray.core.proxy.freedom.DestinationOverride destination_override = 3;</code>
   * @return Whether the destinationOverride field is set.
   */
  boolean hasDestinationOverride();
  /**
   * <code>.v2ray.core.proxy.freedom.DestinationOverride destination_override = 3;</code>
   * @return The destinationOverride.
   */
  com.v2ray.core.proxy.freedom.DestinationOverride getDestinationOverride();
  /**
   * <code>.v2ray.core.proxy.freedom.DestinationOverride destination_override = 3;</code>
   */
  com.v2ray.core.proxy.freedom.DestinationOverrideOrBuilder getDestinationOverrideOrBuilder();

  /**
   * <code>uint32 user_level = 4;</code>
   * @return The userLevel.
   */
  int getUserLevel();
}
