// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/socks/config.proto

package com.v2ray.core.proxy.socks;

public interface ServerConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.proxy.socks.ServerConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.v2ray.core.proxy.socks.AuthType auth_type = 1;</code>
   * @return The enum numeric value on the wire for authType.
   */
  int getAuthTypeValue();
  /**
   * <code>.v2ray.core.proxy.socks.AuthType auth_type = 1;</code>
   * @return The authType.
   */
  com.v2ray.core.proxy.socks.AuthType getAuthType();

  /**
   * <code>map&lt;string, string&gt; accounts = 2;</code>
   */
  int getAccountsCount();
  /**
   * <code>map&lt;string, string&gt; accounts = 2;</code>
   */
  boolean containsAccounts(
      java.lang.String key);
  /**
   * Use {@link #getAccountsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAccounts();
  /**
   * <code>map&lt;string, string&gt; accounts = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAccountsMap();
  /**
   * <code>map&lt;string, string&gt; accounts = 2;</code>
   */

  /* nullable */
java.lang.String getAccountsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; accounts = 2;</code>
   */

  java.lang.String getAccountsOrThrow(
      java.lang.String key);

  /**
   * <code>.v2ray.core.common.net.IPOrDomain address = 3;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.v2ray.core.common.net.IPOrDomain address = 3;</code>
   * @return The address.
   */
  com.v2ray.core.common.net.IPOrDomain getAddress();
  /**
   * <code>.v2ray.core.common.net.IPOrDomain address = 3;</code>
   */
  com.v2ray.core.common.net.IPOrDomainOrBuilder getAddressOrBuilder();

  /**
   * <code>bool udp_enabled = 4;</code>
   * @return The udpEnabled.
   */
  boolean getUdpEnabled();

  /**
   * <code>uint32 timeout = 5 [deprecated = true];</code>
   * @deprecated v2ray.core.proxy.socks.ServerConfig.timeout is deprecated.
   *     See proxy/socks/config.proto;l=38
   * @return The timeout.
   */
  @java.lang.Deprecated int getTimeout();

  /**
   * <code>uint32 user_level = 6;</code>
   * @return The userLevel.
   */
  int getUserLevel();
}
