// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/policy/config.proto

package com.v2ray.core.app.policy;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_policy_Second_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_policy_Second_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_policy_Policy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_policy_Policy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_policy_Policy_Timeout_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_policy_Policy_Timeout_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_policy_Policy_Stats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_policy_Policy_Stats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_policy_Policy_Buffer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_policy_Policy_Buffer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_policy_SystemPolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_policy_SystemPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_policy_SystemPolicy_Stats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_policy_SystemPolicy_Stats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_policy_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_policy_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_app_policy_Config_LevelEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_app_policy_Config_LevelEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027app/policy/config.proto\022\025v2ray.core.ap" +
      "p.policy\"\027\n\006Second\022\r\n\005value\030\001 \001(\r\"\335\003\n\006Po" +
      "licy\0226\n\007timeout\030\001 \001(\0132%.v2ray.core.app.p" +
      "olicy.Policy.Timeout\0222\n\005stats\030\002 \001(\0132#.v2" +
      "ray.core.app.policy.Policy.Stats\0224\n\006buff" +
      "er\030\003 \001(\0132$.v2ray.core.app.policy.Policy." +
      "Buffer\032\335\001\n\007Timeout\0220\n\thandshake\030\001 \001(\0132\035." +
      "v2ray.core.app.policy.Second\0226\n\017connecti" +
      "on_idle\030\002 \001(\0132\035.v2ray.core.app.policy.Se" +
      "cond\0222\n\013uplink_only\030\003 \001(\0132\035.v2ray.core.a" +
      "pp.policy.Second\0224\n\rdownlink_only\030\004 \001(\0132" +
      "\035.v2ray.core.app.policy.Second\0323\n\005Stats\022" +
      "\023\n\013user_uplink\030\001 \001(\010\022\025\n\ruser_downlink\030\002 " +
      "\001(\010\032\034\n\006Buffer\022\022\n\nconnection\030\001 \001(\005\"\267\001\n\014Sy" +
      "stemPolicy\0228\n\005stats\030\001 \001(\0132).v2ray.core.a" +
      "pp.policy.SystemPolicy.Stats\032m\n\005Stats\022\026\n" +
      "\016inbound_uplink\030\001 \001(\010\022\030\n\020inbound_downlin" +
      "k\030\002 \001(\010\022\027\n\017outbound_uplink\030\003 \001(\010\022\031\n\021outb" +
      "ound_downlink\030\004 \001(\010\"\303\001\n\006Config\0227\n\005level\030" +
      "\001 \003(\0132(.v2ray.core.app.policy.Config.Lev" +
      "elEntry\0223\n\006system\030\002 \001(\0132#.v2ray.core.app" +
      ".policy.SystemPolicy\032K\n\nLevelEntry\022\013\n\003ke" +
      "y\030\001 \001(\r\022,\n\005value\030\002 \001(\0132\035.v2ray.core.app." +
      "policy.Policy:\0028\001B`\n\031com.v2ray.core.app." +
      "policyP\001Z)github.com/v2fly/v2ray-core/v4" +
      "/app/policy\252\002\025V2Ray.Core.App.Policyb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_v2ray_core_app_policy_Second_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v2ray_core_app_policy_Second_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_policy_Second_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_v2ray_core_app_policy_Policy_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_v2ray_core_app_policy_Policy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_policy_Policy_descriptor,
        new java.lang.String[] { "Timeout", "Stats", "Buffer", });
    internal_static_v2ray_core_app_policy_Policy_Timeout_descriptor =
      internal_static_v2ray_core_app_policy_Policy_descriptor.getNestedTypes().get(0);
    internal_static_v2ray_core_app_policy_Policy_Timeout_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_policy_Policy_Timeout_descriptor,
        new java.lang.String[] { "Handshake", "ConnectionIdle", "UplinkOnly", "DownlinkOnly", });
    internal_static_v2ray_core_app_policy_Policy_Stats_descriptor =
      internal_static_v2ray_core_app_policy_Policy_descriptor.getNestedTypes().get(1);
    internal_static_v2ray_core_app_policy_Policy_Stats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_policy_Policy_Stats_descriptor,
        new java.lang.String[] { "UserUplink", "UserDownlink", });
    internal_static_v2ray_core_app_policy_Policy_Buffer_descriptor =
      internal_static_v2ray_core_app_policy_Policy_descriptor.getNestedTypes().get(2);
    internal_static_v2ray_core_app_policy_Policy_Buffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_policy_Policy_Buffer_descriptor,
        new java.lang.String[] { "Connection", });
    internal_static_v2ray_core_app_policy_SystemPolicy_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_v2ray_core_app_policy_SystemPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_policy_SystemPolicy_descriptor,
        new java.lang.String[] { "Stats", });
    internal_static_v2ray_core_app_policy_SystemPolicy_Stats_descriptor =
      internal_static_v2ray_core_app_policy_SystemPolicy_descriptor.getNestedTypes().get(0);
    internal_static_v2ray_core_app_policy_SystemPolicy_Stats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_policy_SystemPolicy_Stats_descriptor,
        new java.lang.String[] { "InboundUplink", "InboundDownlink", "OutboundUplink", "OutboundDownlink", });
    internal_static_v2ray_core_app_policy_Config_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_v2ray_core_app_policy_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_policy_Config_descriptor,
        new java.lang.String[] { "Level", "System", });
    internal_static_v2ray_core_app_policy_Config_LevelEntry_descriptor =
      internal_static_v2ray_core_app_policy_Config_descriptor.getNestedTypes().get(0);
    internal_static_v2ray_core_app_policy_Config_LevelEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_app_policy_Config_LevelEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
