// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/vmess/account.proto

package com.v2ray.core.proxy.vmess;

public final class AccountOuterClass {
  private AccountOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_proxy_vmess_Account_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_proxy_vmess_Account_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proxy/vmess/account.proto\022\026v2ray.core." +
      "proxy.vmess\032\035common/protocol/headers.pro" +
      "to\"\205\001\n\007Account\022\n\n\002id\030\001 \001(\t\022\020\n\010alter_id\030\002" +
      " \001(\r\022E\n\021security_settings\030\003 \001(\0132*.v2ray." +
      "core.common.protocol.SecurityConfig\022\025\n\rt" +
      "ests_enabled\030\004 \001(\tBc\n\032com.v2ray.core.pro" +
      "xy.vmessP\001Z*github.com/v2fly/v2ray-core/" +
      "v4/proxy/vmess\252\002\026V2Ray.Core.Proxy.Vmessb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.v2ray.core.common.protocol.Headers.getDescriptor(),
        });
    internal_static_v2ray_core_proxy_vmess_Account_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v2ray_core_proxy_vmess_Account_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_proxy_vmess_Account_descriptor,
        new java.lang.String[] { "Id", "AlterId", "SecuritySettings", "TestsEnabled", });
    com.v2ray.core.common.protocol.Headers.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
