// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/vless/inbound/config.proto

package com.v2ray.core.proxy.vless.inbound;

public interface FallbackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.proxy.vless.inbound.Fallback)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alpn = 1;</code>
   * @return The alpn.
   */
  java.lang.String getAlpn();
  /**
   * <code>string alpn = 1;</code>
   * @return The bytes for alpn.
   */
  com.google.protobuf.ByteString
      getAlpnBytes();

  /**
   * <code>string path = 2;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 2;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string dest = 4;</code>
   * @return The dest.
   */
  java.lang.String getDest();
  /**
   * <code>string dest = 4;</code>
   * @return The bytes for dest.
   */
  com.google.protobuf.ByteString
      getDestBytes();

  /**
   * <code>uint64 xver = 5;</code>
   * @return The xver.
   */
  long getXver();
}
