// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proxy/shadowsocks/config.proto

package com.v2ray.core.proxy.shadowsocks;

/**
 * Protobuf type {@code v2ray.core.proxy.shadowsocks.ServerConfig}
 */
public final class ServerConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.proxy.shadowsocks.ServerConfig)
    ServerConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerConfig.newBuilder() to construct.
  private ServerConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerConfig() {
    network_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerConfig();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.proxy.shadowsocks.Config.internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.proxy.shadowsocks.Config.internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.v2ray.core.proxy.shadowsocks.ServerConfig.class, com.v2ray.core.proxy.shadowsocks.ServerConfig.Builder.class);
  }

  public static final int UDP_ENABLED_FIELD_NUMBER = 1;
  private boolean udpEnabled_;
  /**
   * <pre>
   * UdpEnabled specified whether or not to enable UDP for Shadowsocks.
   * Deprecated. Use 'network' field.
   * </pre>
   *
   * <code>bool udp_enabled = 1 [deprecated = true];</code>
   * @deprecated v2ray.core.proxy.shadowsocks.ServerConfig.udp_enabled is deprecated.
   *     See proxy/shadowsocks/config.proto;l=30
   * @return The udpEnabled.
   */
  @java.lang.Override
  @java.lang.Deprecated public boolean getUdpEnabled() {
    return udpEnabled_;
  }

  public static final int USER_FIELD_NUMBER = 2;
  private com.v2ray.core.common.protocol.User user_;
  /**
   * <code>.v2ray.core.common.protocol.User user = 2;</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>.v2ray.core.common.protocol.User user = 2;</code>
   * @return The user.
   */
  @java.lang.Override
  public com.v2ray.core.common.protocol.User getUser() {
    return user_ == null ? com.v2ray.core.common.protocol.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.v2ray.core.common.protocol.User user = 2;</code>
   */
  @java.lang.Override
  public com.v2ray.core.common.protocol.UserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int NETWORK_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Integer> network_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, com.v2ray.core.common.net.Network> network_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, com.v2ray.core.common.net.Network>() {
            public com.v2ray.core.common.net.Network convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              com.v2ray.core.common.net.Network result = com.v2ray.core.common.net.Network.valueOf(from);
              return result == null ? com.v2ray.core.common.net.Network.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
   * @return A list containing the network.
   */
  @java.lang.Override
  public java.util.List<com.v2ray.core.common.net.Network> getNetworkList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, com.v2ray.core.common.net.Network>(network_, network_converter_);
  }
  /**
   * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
   * @return The count of network.
   */
  @java.lang.Override
  public int getNetworkCount() {
    return network_.size();
  }
  /**
   * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
   * @param index The index of the element to return.
   * @return The network at the given index.
   */
  @java.lang.Override
  public com.v2ray.core.common.net.Network getNetwork(int index) {
    return network_converter_.convert(network_.get(index));
  }
  /**
   * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
   * @return A list containing the enum numeric values on the wire for network.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getNetworkValueList() {
    return network_;
  }
  /**
   * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of network at the given index.
   */
  @java.lang.Override
  public int getNetworkValue(int index) {
    return network_.get(index);
  }
  private int networkMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (udpEnabled_ != false) {
      output.writeBool(1, udpEnabled_);
    }
    if (user_ != null) {
      output.writeMessage(2, getUser());
    }
    if (getNetworkList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(networkMemoizedSerializedSize);
    }
    for (int i = 0; i < network_.size(); i++) {
      output.writeEnumNoTag(network_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (udpEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, udpEnabled_);
    }
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUser());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < network_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(network_.get(i));
      }
      size += dataSize;
      if (!getNetworkList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }networkMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.v2ray.core.proxy.shadowsocks.ServerConfig)) {
      return super.equals(obj);
    }
    com.v2ray.core.proxy.shadowsocks.ServerConfig other = (com.v2ray.core.proxy.shadowsocks.ServerConfig) obj;

    if (getUdpEnabled()
        != other.getUdpEnabled()) return false;
    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (!network_.equals(other.network_)) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UDP_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUdpEnabled());
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (getNetworkCount() > 0) {
      hash = (37 * hash) + NETWORK_FIELD_NUMBER;
      hash = (53 * hash) + network_.hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.v2ray.core.proxy.shadowsocks.ServerConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.v2ray.core.proxy.shadowsocks.ServerConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code v2ray.core.proxy.shadowsocks.ServerConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.proxy.shadowsocks.ServerConfig)
      com.v2ray.core.proxy.shadowsocks.ServerConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.proxy.shadowsocks.Config.internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.proxy.shadowsocks.Config.internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.v2ray.core.proxy.shadowsocks.ServerConfig.class, com.v2ray.core.proxy.shadowsocks.ServerConfig.Builder.class);
    }

    // Construct using com.v2ray.core.proxy.shadowsocks.ServerConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      udpEnabled_ = false;

      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      network_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.proxy.shadowsocks.Config.internal_static_v2ray_core_proxy_shadowsocks_ServerConfig_descriptor;
    }

    @java.lang.Override
    public com.v2ray.core.proxy.shadowsocks.ServerConfig getDefaultInstanceForType() {
      return com.v2ray.core.proxy.shadowsocks.ServerConfig.getDefaultInstance();
    }

    @java.lang.Override
    public com.v2ray.core.proxy.shadowsocks.ServerConfig build() {
      com.v2ray.core.proxy.shadowsocks.ServerConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.v2ray.core.proxy.shadowsocks.ServerConfig buildPartial() {
      com.v2ray.core.proxy.shadowsocks.ServerConfig result = new com.v2ray.core.proxy.shadowsocks.ServerConfig(this);
      int from_bitField0_ = bitField0_;
      result.udpEnabled_ = udpEnabled_;
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        network_ = java.util.Collections.unmodifiableList(network_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.network_ = network_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.v2ray.core.proxy.shadowsocks.ServerConfig) {
        return mergeFrom((com.v2ray.core.proxy.shadowsocks.ServerConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.v2ray.core.proxy.shadowsocks.ServerConfig other) {
      if (other == com.v2ray.core.proxy.shadowsocks.ServerConfig.getDefaultInstance()) return this;
      if (other.getUdpEnabled() != false) {
        setUdpEnabled(other.getUdpEnabled());
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (!other.network_.isEmpty()) {
        if (network_.isEmpty()) {
          network_ = other.network_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureNetworkIsMutable();
          network_.addAll(other.network_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              udpEnabled_ = input.readBool();

              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getUserFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 18
            case 24: {
              int tmpRaw = input.readEnum();
              ensureNetworkIsMutable();
              network_.add(tmpRaw);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int tmpRaw = input.readEnum();
                ensureNetworkIsMutable();
                network_.add(tmpRaw);
              }
              input.popLimit(oldLimit);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean udpEnabled_ ;
    /**
     * <pre>
     * UdpEnabled specified whether or not to enable UDP for Shadowsocks.
     * Deprecated. Use 'network' field.
     * </pre>
     *
     * <code>bool udp_enabled = 1 [deprecated = true];</code>
     * @deprecated v2ray.core.proxy.shadowsocks.ServerConfig.udp_enabled is deprecated.
     *     See proxy/shadowsocks/config.proto;l=30
     * @return The udpEnabled.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean getUdpEnabled() {
      return udpEnabled_;
    }
    /**
     * <pre>
     * UdpEnabled specified whether or not to enable UDP for Shadowsocks.
     * Deprecated. Use 'network' field.
     * </pre>
     *
     * <code>bool udp_enabled = 1 [deprecated = true];</code>
     * @deprecated v2ray.core.proxy.shadowsocks.ServerConfig.udp_enabled is deprecated.
     *     See proxy/shadowsocks/config.proto;l=30
     * @param value The udpEnabled to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setUdpEnabled(boolean value) {
      
      udpEnabled_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UdpEnabled specified whether or not to enable UDP for Shadowsocks.
     * Deprecated. Use 'network' field.
     * </pre>
     *
     * <code>bool udp_enabled = 1 [deprecated = true];</code>
     * @deprecated v2ray.core.proxy.shadowsocks.ServerConfig.udp_enabled is deprecated.
     *     See proxy/shadowsocks/config.proto;l=30
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearUdpEnabled() {
      
      udpEnabled_ = false;
      onChanged();
      return this;
    }

    private com.v2ray.core.common.protocol.User user_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.v2ray.core.common.protocol.User, com.v2ray.core.common.protocol.User.Builder, com.v2ray.core.common.protocol.UserOrBuilder> userBuilder_;
    /**
     * <code>.v2ray.core.common.protocol.User user = 2;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>.v2ray.core.common.protocol.User user = 2;</code>
     * @return The user.
     */
    public com.v2ray.core.common.protocol.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.v2ray.core.common.protocol.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.v2ray.core.common.protocol.User user = 2;</code>
     */
    public Builder setUser(com.v2ray.core.common.protocol.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.v2ray.core.common.protocol.User user = 2;</code>
     */
    public Builder setUser(
        com.v2ray.core.common.protocol.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.v2ray.core.common.protocol.User user = 2;</code>
     */
    public Builder mergeUser(com.v2ray.core.common.protocol.User value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.v2ray.core.common.protocol.User.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.v2ray.core.common.protocol.User user = 2;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.v2ray.core.common.protocol.User user = 2;</code>
     */
    public com.v2ray.core.common.protocol.User.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.v2ray.core.common.protocol.User user = 2;</code>
     */
    public com.v2ray.core.common.protocol.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.v2ray.core.common.protocol.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.v2ray.core.common.protocol.User user = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.v2ray.core.common.protocol.User, com.v2ray.core.common.protocol.User.Builder, com.v2ray.core.common.protocol.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.v2ray.core.common.protocol.User, com.v2ray.core.common.protocol.User.Builder, com.v2ray.core.common.protocol.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private java.util.List<java.lang.Integer> network_ =
      java.util.Collections.emptyList();
    private void ensureNetworkIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        network_ = new java.util.ArrayList<java.lang.Integer>(network_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @return A list containing the network.
     */
    public java.util.List<com.v2ray.core.common.net.Network> getNetworkList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.v2ray.core.common.net.Network>(network_, network_converter_);
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @return The count of network.
     */
    public int getNetworkCount() {
      return network_.size();
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @param index The index of the element to return.
     * @return The network at the given index.
     */
    public com.v2ray.core.common.net.Network getNetwork(int index) {
      return network_converter_.convert(network_.get(index));
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @param index The index to set the value at.
     * @param value The network to set.
     * @return This builder for chaining.
     */
    public Builder setNetwork(
        int index, com.v2ray.core.common.net.Network value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNetworkIsMutable();
      network_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @param value The network to add.
     * @return This builder for chaining.
     */
    public Builder addNetwork(com.v2ray.core.common.net.Network value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureNetworkIsMutable();
      network_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @param values The network to add.
     * @return This builder for chaining.
     */
    public Builder addAllNetwork(
        java.lang.Iterable<? extends com.v2ray.core.common.net.Network> values) {
      ensureNetworkIsMutable();
      for (com.v2ray.core.common.net.Network value : values) {
        network_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetwork() {
      network_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @return A list containing the enum numeric values on the wire for network.
     */
    public java.util.List<java.lang.Integer>
    getNetworkValueList() {
      return java.util.Collections.unmodifiableList(network_);
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of network at the given index.
     */
    public int getNetworkValue(int index) {
      return network_.get(index);
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @param index The index to set the value at.
     * @param value The enum numeric value on the wire for network to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkValue(
        int index, int value) {
      ensureNetworkIsMutable();
      network_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @param value The enum numeric value on the wire for network to add.
     * @return This builder for chaining.
     */
    public Builder addNetworkValue(int value) {
      ensureNetworkIsMutable();
      network_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @param values The enum numeric values on the wire for network to add.
     * @return This builder for chaining.
     */
    public Builder addAllNetworkValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureNetworkIsMutable();
      for (int value : values) {
        network_.add(value);
      }
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.proxy.shadowsocks.ServerConfig)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.proxy.shadowsocks.ServerConfig)
  private static final com.v2ray.core.proxy.shadowsocks.ServerConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.v2ray.core.proxy.shadowsocks.ServerConfig();
  }

  public static com.v2ray.core.proxy.shadowsocks.ServerConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerConfig>
      PARSER = new com.google.protobuf.AbstractParser<ServerConfig>() {
    @java.lang.Override
    public ServerConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.v2ray.core.proxy.shadowsocks.ServerConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

